// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkcabkygjxrijuusqopc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrY2Fia3lnanhyaWp1dXNxb3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjA4OTYsImV4cCI6MjA3MDU5Njg5Nn0.dteAOEXME3I9xq6-TYusA5_FteCq4eKUd2PTIQylQyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});